# Generated by Django 3.1.5 on 2021-06-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210613_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user_id',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
