# Generated by Django 3.1.5 on 2021-06-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_appointment_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
